name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install customtkinter requests psutil
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
    
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico --name "ZCraft Panel" main.py
    
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/*.exe
